from tkinter import *
from tkinter import ttk

def submit_form():
# Create a new style with the arrow element
    # style = ttk.Style()
    # style.configure('Custom.TMenubutton', arrow=True)
    # Retrieve the entered data
    ubicacion_geografica_dep = entry_ubicacion_dep.get()
    ubicacion_geografica_municipio = entry_ubicacion_municipio.get()
    entidad = entry_entidad.get()
    correo = entry_correo.get()
    direccion = entry_direccion.get()
    telefonos = entry_telefonos.get()
    equipo = entry_equipo.get()
    forma_adquisicion = var_forma_adquisicion.get()
    marca = entry_marca.get()
    documento = entry_documento.get()
    factura = entry_factura.get()
    modelo = entry_modelo.get()
    anio_fabricacion = entry_anio_fabricacion.get()
    serie = entry_serie.get()
    fecha_compra = entry_fecha_compra.get()
    fecha_instalacion = entry_fecha_instalacion.get()
    inicio_operacion = entry_inicio_operacion.get()
    vencimiento_garantia = entry_vencimiento_garantia.get()
    proveedor = entry_proveedor.get()
    fabricante = entry_fabricante.get()
    tension = entry_tension.get()
    corriente = entry_corriente.get()
    peso = entry_peso.get()
    potencia = entry_potencia.get()
    frecuencia = entry_frecuencia.get()
    velocidad = entry_velocidad.get()
    presion = entry_presion.get()
    rango_temperatura = entry_rango_temperatura.get()
    tecnologia_predominante = entry_tecnologia_predominante.get()
    rango_voltaje = entry_rango_voltaje.get()
    rango_presion = entry_rango_presion.get()
    rango_humedad = entry_rango_humedad.get()
    rango_corriente = entry_rango_corriente.get()
    rango_frecuencia = entry_rango_frecuencia.get()
    clasificacion_riesgo = var_clasificacion_riesgo.get()
    periodicidad_mantenimiento = entry_periodicidad_mantenimiento.get()
    requiere_calibracion = var_requiere_calibracion.get()
    observaciones = text_observaciones.get("1.0", END)

    # Print or process the collected data as needed
    print("Ubicación Geográfica - Departamento:", ubicacion_geografica_dep)
    print("Ubicación Geográfica - Municipio:", ubicacion_geografica_municipio)
    print("Entidad:", entidad)
    print("Correo:", correo)
    print("Dirección:", direccion)
    print("Teléfonos:", telefonos)
    print("Equipo:", equipo)
    print("Forma de Adquisición:", forma_adquisicion)
    print("Marca:", marca)
    print("Documento:", documento)
    print("Factura:", factura)
    print("Modelo:", modelo)
    print("Año de Fabricación:", anio_fabricacion)
    print("Serie N°:", serie)
    print("Fecha de Compra:", fecha_compra)
    print("Fecha de Instalación:", fecha_instalacion)
    print("Inicio de Operación:", inicio_operacion)
    print("Vencimiento de Garantía:", vencimiento_garantia)
    print("Proveedor:", proveedor)
    print("Fabricante:", fabricante)
    print("Tensión:", tension)
    print("Corriente:", corriente)
    print("Peso:", peso)
    print("Potencia:", potencia)
    print("Frecuencia:", frecuencia)
    print("Velocidad:", velocidad)
    print("Presión:", presion)
    print("Rango de Temperatura:", rango_temperatura)
    print("Tecnología Predominante:", tecnologia_predominante)
    print("Rango de Voltaje:", rango_voltaje)
    print("Rango de Presión:", rango_presion)
    print("Rango de Humedad:", rango_humedad)
    print("Rango de Corriente:", rango_corriente)
    print("Rango de Frecuencia:", rango_frecuencia)
    print("Clasificación según Nivel de Riesgo:", clasificacion_riesgo)
    print("Periodicidad del Mantenimiento:", periodicidad_mantenimiento)
    print("Requiere Calibración:", requiere_calibracion)
    print("Observaciones:", observaciones)

win = Tk()
win.title('Formulario Hoja de Vida')
win.geometry('720x900')

# Create a canvas to hold the form
canvas = Canvas(win, )
canvas.pack(side=LEFT, fill=BOTH, expand=True)

# Create a scrollbar and associate it with the canvas
scrollbar = Scrollbar(win, orient=VERTICAL, command=canvas.yview)
scrollbar.pack(side=RIGHT, fill=Y)

# Configure the canvas to use the scrollbar
canvas.configure(yscrollcommand=scrollbar.set)
canvas.bind('<Configure>', lambda e: canvas.configure(scrollregion=canvas.bbox('all')))

# Create a frame to hold the form elements
form_frame = Frame(canvas)
form_frame.grid(row=0, column=0, columnspan=2, sticky='news')
canvas.create_window((0, 0), window=form_frame, anchor='nw')

# Labels
label_ubicacion_dep = Label(form_frame, text="Departamento")
label_ubicacion_municipio = Label(form_frame, text="Municipio")
label_entidad = Label(form_frame, text="Entidad")
label_correo = Label(form_frame, text="Correo")
label_direccion = Label(form_frame, text="Dirección")
label_telefonos = Label(form_frame, text="Teléfonos")
label_equipo = Label(form_frame, text="Equipo")
label_forma_adquisicion = Label(form_frame, text="Forma de Adquisición")
label_marca = Label(form_frame, text="Marca")
label_documento = Label(form_frame, text="Documento")
label_factura = Label(form_frame, text="Factura")
label_modelo = Label(form_frame, text="Modelo")
label_anio_fabricacion = Label(form_frame, text="Año de Fabricación")
label_serie = Label(form_frame, text="Serie N°")
label_fecha_compra = Label(form_frame, text="Fecha de Compra")
label_fecha_instalacion = Label(form_frame, text="Fecha de Instalación")
label_inicio_operacion = Label(form_frame, text="Inicio de Operación")
label_vencimiento_garantia = Label(form_frame, text="Vencimiento de Garantía")
label_proveedor = Label(form_frame, text="Proveedor")
label_fabricante = Label(form_frame, text="Fabricante")
label_tension = Label(form_frame, text="Tensión (V)")
label_corriente = Label(form_frame, text="Corriente (A)")
label_peso = Label(form_frame, text="Peso")
label_potencia = Label(form_frame, text="Potencia (W)")
label_frecuencia = Label(form_frame, text="Frecuencia (Hz)")
label_velocidad = Label(form_frame, text="Velocidad")
label_presion = Label(form_frame, text="Presión")
label_rango_temperatura = Label(form_frame, text="Rango de Temperatura")
label_tecnologia_predominante = Label(form_frame, text="Tecnología Predominante")
label_rango_voltaje = Label(form_frame, text="Rango de Voltaje")
label_rango_presion = Label(form_frame, text="Rango de Presión")
label_rango_humedad = Label(form_frame, text="Rango de Humedad")
label_rango_corriente = Label(form_frame, text="Rango de Corriente")
label_rango_frecuencia = Label(form_frame, text="Rango de Frecuencia")
label_clasificacion_riesgo = Label(form_frame, text="Clasificación según Nivel de Riesgo")
label_periodicidad_mantenimiento = Label(form_frame, text="Periodicidad del Mantenimiento")
label_requiere_calibracion = Label(form_frame, text="Requiere Calibración")
label_observaciones = Label(form_frame, text="Observaciones")

# Entry fields
entry_ubicacion_dep = Entry(form_frame)
entry_ubicacion_municipio = Entry(form_frame)
entry_entidad = Entry(form_frame)
entry_correo = Entry(form_frame)
entry_direccion = Entry(form_frame)
entry_telefonos = Entry(form_frame)
entry_equipo = Entry(form_frame)
var_forma_adquisicion = StringVar(form_frame)
optionmenu_forma_adquisicion = OptionMenu(form_frame, var_forma_adquisicion, "1. Compra", "2. Donación", "3. Incautación")
entry_marca = Entry(form_frame)
entry_documento = Entry(form_frame)
entry_factura = Entry(form_frame)
entry_modelo = Entry(form_frame)
entry_anio_fabricacion = Entry(form_frame)
entry_serie = Entry(form_frame)
entry_fecha_compra = Entry(form_frame)
entry_fecha_instalacion = Entry(form_frame)
entry_inicio_operacion = Entry(form_frame)
entry_vencimiento_garantia = Entry(form_frame)
entry_proveedor = Entry(form_frame)
entry_fabricante = Entry(form_frame)
entry_tension = Entry(form_frame)
entry_corriente = Entry(form_frame)
entry_peso = Entry(form_frame)
entry_potencia = Entry(form_frame)
entry_frecuencia = Entry(form_frame)
entry_velocidad = Entry(form_frame)
entry_presion = Entry(form_frame)
entry_rango_temperatura = Entry(form_frame)
entry_tecnologia_predominante = Entry(form_frame)
entry_rango_voltaje = Entry(form_frame)
entry_rango_presion = Entry(form_frame)
entry_rango_humedad = Entry(form_frame)
entry_rango_corriente = Entry(form_frame)
entry_rango_frecuencia = Entry(form_frame)
var_clasificacion_riesgo = StringVar(form_frame)
var_clasificacion_riesgo.set("CLASE I")
optionmenu_clasificacion_riesgo = ttk.Combobox(form_frame, textvariable=var_clasificacion_riesgo, values=["CLASE I", "CLASE IA", "CLASE IIB", "CLASE III"])
optionmenu_clasificacion_riesgo.config(width=15, state="readonly", style='Custom.TCombobox')

# Create a new style with the arrow element
style = ttk.Style()
style.configure('Custom.TCombobox', arrow=True)
entry_periodicidad_mantenimiento = Entry(form_frame)
var_requiere_calibracion = BooleanVar(form_frame)
checkbutton_requiere_calibracion = Checkbutton(form_frame, text="Sí", variable=var_requiere_calibracion)
text_observaciones = Text(form_frame, height=10, width=50)

# Button
submit_button = Button(form_frame, text="Submit", command=submit_form)

# Grid layout
label_ubicacion_dep.grid(row=0, column=0, sticky=W, padx=10, pady=5)
label_ubicacion_municipio.grid(row=1, column=0, sticky=W, padx=10, pady=5)
label_entidad.grid(row=2, column=0, sticky=W, padx=10, pady=5)
label_correo.grid(row=3, column=0, sticky=W, padx=10, pady=5)
label_direccion.grid(row=4, column=0, sticky=W, padx=10, pady=5)
label_telefonos.grid(row=5, column=0, sticky=W, padx=10, pady=5)
label_equipo.grid(row=6, column=0, sticky=W, padx=10, pady=5)
label_forma_adquisicion.grid(row=7, column=0, sticky=W, padx=10, pady=5)
label_marca.grid(row=8, column=0, sticky=W, padx=10, pady=5)
label_documento.grid(row=9, column=0, sticky=W, padx=10, pady=5)
label_factura.grid(row=10, column=0, sticky=W, padx=10, pady=5)
label_modelo.grid(row=11, column=0, sticky=W, padx=10, pady=5)
label_anio_fabricacion.grid(row=12, column=0, sticky=W, padx=10, pady=5)
label_serie.grid(row=13, column=0, sticky=W, padx=10, pady=5)
label_fecha_compra.grid(row=14, column=0, sticky=W, padx=10, pady=5)
label_fecha_instalacion.grid(row=15, column=0, sticky=W, padx=10, pady=5)
label_inicio_operacion.grid(row=16, column=0, sticky=W, padx=10, pady=5)
label_vencimiento_garantia.grid(row=17, column=0, sticky=W, padx=10, pady=5)
label_proveedor.grid(row=18, column=0, sticky=W, padx=10, pady=5)
label_fabricante.grid(row=19, column=0, sticky=W, padx=10, pady=5)
label_tension.grid(row=20, column=0, sticky=W, padx=10, pady=5)
label_corriente.grid(row=21, column=0, sticky=W, padx=10, pady=5)
label_peso.grid(row=22, column=0, sticky=W, padx=10, pady=5)
label_potencia.grid(row=23, column=0, sticky=W, padx=10, pady=5)
label_frecuencia.grid(row=24, column=0, sticky=W, padx=10, pady=5)
label_velocidad.grid(row=25, column=0, sticky=W, padx=10, pady=5)
label_presion.grid(row=26, column=0, sticky=W, padx=10, pady=5)
label_rango_temperatura.grid(row=27, column=0, sticky=W, padx=10, pady=5)
label_tecnologia_predominante.grid(row=28, column=0, sticky=W, padx=10, pady=5)
label_rango_voltaje.grid(row=29, column=0, sticky=W, padx=10, pady=5)
label_rango_presion.grid(row=30, column=0, sticky=W, padx=10, pady=5)
label_rango_humedad.grid(row=31, column=0, sticky=W, padx=10, pady=5)
label_rango_corriente.grid(row=32, column=0, sticky=W, padx=10, pady=5)
label_rango_frecuencia.grid(row=33, column=0, sticky=W, padx=10, pady=5)
label_clasificacion_riesgo.grid(row=34, column=0, sticky=W, padx=10, pady=5)
label_periodicidad_mantenimiento.grid(row=35, column=0, sticky=W, padx=10, pady=5)
label_requiere_calibracion.grid(row=36, column=0, sticky=W, padx=10, pady=5)
label_observaciones.grid(row=37, column=0, sticky=W, padx=10, pady=5)

entry_ubicacion_dep.grid(row=0, column=1, padx=10, pady=5)
entry_ubicacion_municipio.grid(row=1, column=1, padx=10, pady=5)
entry_entidad.grid(row=2, column=1, padx=10, pady=5)
entry_correo.grid(row=3, column=1, padx=10, pady=5)
entry_direccion.grid(row=4, column=1, padx=10, pady=5)
entry_telefonos.grid(row=5, column=1, padx=10, pady=5)
entry_equipo.grid(row=6, column=1, padx=10, pady=5)
optionmenu_forma_adquisicion.grid(row=7, column=1, padx=10, pady=5)
entry_marca.grid(row=8, column=1, padx=10, pady=5)
entry_documento.grid(row=9, column=1, padx=10, pady=5)
entry_factura.grid(row=10, column=1, padx=10, pady=5)
entry_modelo.grid(row=11, column=1, padx=10, pady=5)
entry_anio_fabricacion.grid(row=12, column=1, padx=10, pady=5)
entry_serie.grid(row=13, column=1, padx=10, pady=5)
entry_fecha_compra.grid(row=14, column=1, padx=10, pady=5)
entry_fecha_instalacion.grid(row=15, column=1, padx=10, pady=5)
entry_inicio_operacion.grid(row=16, column=1, padx=10, pady=5)
entry_vencimiento_garantia.grid(row=17, column=1, padx=10, pady=5)
entry_proveedor.grid(row=18, column=1, padx=10, pady=5)
entry_fabricante.grid(row=19, column=1, padx=10, pady=5)
entry_tension.grid(row=20, column=1, padx=10, pady=5)
entry_corriente.grid(row=21, column=1, padx=10, pady=5)
entry_peso.grid(row=22, column=1, padx=10, pady=5)
entry_potencia.grid(row=23, column=1, padx=10, pady=5)
entry_frecuencia.grid(row=24, column=1, padx=10, pady=5)
entry_velocidad.grid(row=25, column=1, padx=10, pady=5)
entry_presion.grid(row=26, column=1, padx=10, pady=5)
entry_rango_temperatura.grid(row=27, column=1, padx=10, pady=5)
entry_tecnologia_predominante.grid(row=28, column=1, padx=10, pady=5)
entry_rango_voltaje.grid(row=29, column=1, padx=10, pady=5)
entry_rango_presion.grid(row=30, column=1, padx=10, pady=5)
entry_rango_humedad.grid(row=31, column=1, padx=10, pady=5)
entry_rango_corriente.grid(row=32, column=1, padx=10, pady=5)
entry_rango_frecuencia.grid(row=33, column=1, padx=10, pady=5)
optionmenu_clasificacion_riesgo.grid(row=34, column=1, padx=10, pady=5)
entry_periodicidad_mantenimiento.grid(row=35, column=1, padx=10, pady=5)
checkbutton_requiere_calibracion.grid(row=36, column=1, padx=10, pady=5)
text_observaciones.grid(row=37, column=1, padx=10, pady=5)

submit_button.grid(row=38, column=1, pady=10)

win.mainloop()
